### ISSUE TITLE
Auto correct / prediction on the subject

### ISSUE THREAD

**Issue by grumpy-one** [Infomaniak/android-kMail#1051]
**Is your feature request related to a problem? Please describe.**
Can't use the dictonary (auto correct/prediction) on the subject field

**Describe the solution you'd like**
I will can write the object of my email and use the auto correct/prediction of my keypad.

**Describe alternatives you've considered**
I'm adding it as a feature because it's not urgent and I don't know if Infomaniak has deliberately disabled this.

**Additional context**
I use Microsoft SwiftKey on Android 13.

**Comment by JorisBodin** [comment]
This is a problem we only have with the "SwiftKey" keyboard app.

We have indicated the correct type for this input. Other keyboards like Gboard don't have this problem.
https://github.com/Infomaniak/android-kMail/blob/c963b017d71128b79b6d7c9f9a465e27d9ef69a8/app/src/main/res/layout/fragment_new_message.xml#L215
