### ISSUE TITLE
No Push Notifications for new E-Mails

### ISSUE THREAD

**Issue by JPDohle** [Infomaniak/android-kMail#1141]
**Description**
On my phone I do not receive Push notifications when new E-Mails are received.

**Steps to reproduce**
1. To be on the safe side, I closed all other Webmail sessions and IMAP clients which are connected to the account.
2. Checked that ikMail is functional.
3. Pressed Home button to leave ikMail.
4. Send a test E-Mail to the Infomaniak account from a separate E-Mail address / account.
5. Waiting more than 10 minutes, no push notification is shown.
6. Opening ikMail.
7. The new test E-Mail is shown.

**Expected behavior**
ikMail should immediately show notifications for new E-Mails, even when the app is not in the foreground.  
With other E-Mail app (FairEmail) it is working as expected via IMAP connection.  
All other settings, e. g. for power saving and permissions are the same for ikMail and FairEmail.

**Screenshots**
Below are the notification settings for ikMail.

App Notification settings of ikMail:
![image](https://github.com/Infomaniak/android-kMail/assets/83199927/fea92813-7f3d-4716-a42d-654acde74db4)

Notification settings for New Emails:
![image](https://github.com/Infomaniak/android-kMail/assets/83199927/f97b5962-7a1b-43a3-8a34-394cf02f7681)

**Smartphone**
 - Xiaomi Redmi Note 10S (M2101K7BNY)
 - Android version: 13 TP1A.220624.014
 - App version: 1.0.4

**Comment by JorisBodin** [comment]
The [1.0.5](https://github.com/Infomaniak/android-kMail/releases/tag/1.0.5) corrige le problème
It will be available within 1-2 hours

https://github.com/Infomaniak/android-kMail/pull/1150

**Comment by cyberdarius** [comment]
I have the same situation and the same problem: no push notification.

App version 1.0.14 from Playstore version.

**Comment by JorisBodin** [comment]
Thanks for your feedback @cyberdarius 

Personally I also have a Pixel 6 with "battery optimized" for Infomaniak Mail and I receive notifications.

We thought it was the modified Android (other than google pixel) that could have the problem.

Since our application is not a GAFAM application, it's not a whitelist.
I think we're going to have to suggest disabling battery optimization in the interface for people who have problems receiving notifications 😔

We use firebase notifications, so it's official android, I don't understand why there's such behavior...

https://stackoverflow.com/questions/56154811/why-am-i-not-able-to-recive-a-push-notification-when-my-app-is-battery-optimized

**Comment by JorisBodin** [comment]
@cyberdarius Do you have the "Battery saver" mode enabled?
![image](https://github.com/Infomaniak/android-kMail/assets/2796439/fe2819a6-537c-461b-9711-93117111f421)

**Comment by cyberdarius** [comment]
> @cyberdarius Do you have the "Battery saver" mode enabled?
> 
> ![image](https://user-images.githubusercontent.com/2796439/274860784-fe2819a6-537c-461b-9711-93117111f421.png)

No. Battery saver not enabled.
I have no particular battery profile enabled. Pixel 6 defaults (Adaptive battery enabled). 

But other email clients (like proton) works correctly with optimized battery profile

**Comment by cyberdarius** [comment]
> Thanks for your feedback @cyberdarius
> 
> Personally I also have a Pixel 6 with "battery optimized" for Infomaniak Mail and I receive notifications.
> 
> We thought it was the modified Android (other than google pixel) that could have the problem.
> 
> Since our application is not a GAFAM application, it's not a whitelist. I think we're going to have to suggest disabling battery optimization in the interface for people who have problems receiving notifications 😔
> 
> We use firebase notifications, so it's official android, I don't understand why there's such behavior...
> 
> https://stackoverflow.com/questions/56154811/why-am-i-not-able-to-recive-a-push-notification-when-my-app-is-battery-optimized

Thanks for your prompt support. 

Yes, it's very strange.

I confirm that with disabling battery optimization, the notifications works correctly. 

I re-tried to set battery optimization  => no notification.

after

Disabling battery optimization => works.

**Comment by ctout76** [comment]
Hi,
Same problem with Pixel 7 - GrapheneOS Android 14 - Infomaniak Mail 1.1.2 - No battery optimisation
🙁

**Comment by JorisBodin** [comment]
@ctout76 Does it work better today? Phone restarted? Application launched?
We've realised that Google transmits notifications as it sees fit, depending on how the application is used.
We'll have to sync in the background every x minutes to make sure we're receiving the notifications.
We see the same behaviour with gmail

**Comment by ctout76** [comment]
> @ctout76 Does it work better today? Phone restarted? Application launched? We've realised that Google transmits notifications as it sees fit, depending on how the application is used. We'll have to sync in the background every x minutes to make sure we're receiving the notifications. We see the same behaviour with gmail

No change... (Phone restarted, application launched) 🙁

**Comment by ctout76** [comment]
> Your email address is an alias?

No, Can I send it to you privately?

**Comment by ctout76** [comment]
> Your email address is an alias?

No,it is linked to an Infomaniak domain name with kSuite

**Comment by JorisBodin** [comment]
We check

**Comment by JorisBodin** [comment]
@ctout76 
Have you been doing this since the beginning or just for a while?
The notifications are only for inbox, if you have Sieve rules, it doesn't work.

**Comment by ctout76** [comment]
It worked perfectly before, I used the app since the beta version without problems. There are no rules.

**Comment by JorisBodin** [comment]
@ctout76 and now?

**Comment by ctout76** [comment]
> @ctout76 and now?

Now, it's OK !👍👍👍

**Comment by ctout76** [comment]
Hi, again, no notifications when receiving emails... 🙁

**Comment by toketin** [comment]
Hi, sorry if I open again this issue, but I'm experiencing the same one. I'm on grapheneos (Android 15), I've tried also to disable the battery optimization on Infomaniak mail app, but I'm still getting new mail with lag.

**Comment by JorisBodin** [comment]
If you don't have the google play service, you can't receive push notifications, so it's a worker that runs every 15 minutes to update your emails and notify you if there are any new emails.

**Comment by toketin** [comment]
Ok thank you! Yes I've the Google play service sandboxed as default for grapheneos.

Thanks!
