### ISSUE TITLE
Clicking on notification directly starts a response

### ISSUE THREAD

**Issue by JPDohle** [Infomaniak/android-kMail#1159]
**Description**
When clicking on the notification for a new mail, ikMail is opened and immediately starts a response to that mail.

**Steps to reproduce**
1. Wait until a new mail is received and ikMail is not opened
2. Click somewhere on the Android notification (not on the ANTWORT link)
3. ikMail starts a response to that mail

**Expected behavior**
Usually most users want to read a new mail first.  
A response is probably only required in very few cases.

Clicking on the notification should just open the mail.

**Screenshots**
Clicking somewhere near the yellow marker:
![image](https://github.com/Infomaniak/android-kMail/assets/83199927/bebea12d-392c-4792-b755-1f33cfa80459)

ikMail directly starts a response to that mail:
![image](https://github.com/Infomaniak/android-kMail/assets/83199927/9e92fd9f-c454-4be7-9f8b-48900542f814)

**Smartphone**
- Device: Xiaomi Redmi Note 10S (M2101K7BNY)
- Android version: 13 TP1A.220624.014
- App version: 1.0.5

**Comment by JorisBodin** [comment]
Fixed 50 min ago: https://github.com/Infomaniak/android-kMail/pull/1157

Build 3 of 1.0.5 is being reviewed by google, available in -1H
