### ISSUE TITLE
Unitary message view

### ISSUE THREAD

**Issue by manuscule** [Infomaniak/android-kMail#1254]
I'm not a fan of the threaded messages view, please add unitary message option as initially planned within settings v1.

I'd like to be able to view each massage as one meaaage, not the threaded conversation view.. This should be a setting as in the webmail application.

**Comment by JorisBodin** [comment]
Now available in 1.0.9
https://github.com/Infomaniak/android-kMail/releases/tag/1.0.9

**Comment by manuscule** [comment]
OK thanks, looking forward to seeing this release available in f-droid.
