### ISSUE TITLE
f-droid version backlog

### ISSUE THREAD

**Issue by manuscule** [Infomaniak/android-kMail#1299]
*Note: Please write your issue only in english*

**Description**
Not sure if it is an issue on your side or on f-droid, but I'm sure you'll figure it out. In github, I see version 1.0.10, but on f-droid, it's still 10.0.8. I know that sometimes it takes a few days for the repository to update, but we're two versions behind right now.

**Steps to reproduce**
1. Go to https://f-droid.org/fr/packages/com.infomaniak.mail/
2. Look at available versions (10.0.8 as of today).
3. Compare to github version (10.0.10 as of today).

**Expected behavior**
Ensure version updates follow on the f-droid repository (a few days delay is OK but with two missing versions, there seems to be a problem).

**Comment by JorisBodin** [comment]
@manuscule This is a problem with f-droid.
They take a while to update apps.

If you install it from the beta playstore, you'll get the update within the hour. And with push notifications.

**Comment by manuscule** [comment]
@JorisBodin thanks for youf feedback. 10.0.9 is nos available... I don't use Google play services so beta play store is not an option for me.
Maybe this could help speeding up the process ?
https://f-droid.org/docs/Update_Processing/
