### ISSUE TITLE
Can not Register New Account

### ISSUE THREAD

**Issue by fdciabdul** [Infomaniak/android-kMail#1347]
*Note: Please write your issue only in english*

**Description**

**Steps to reproduce**
1. Go to app
2. Click on Register
3. Back To Previous Page

**Expected behavior**
well i'm really interested with this app and service.

**Screenshots**

https://github.com/Infomaniak/android-kMail/assets/31664438/764ad298-a8d2-4aa3-b938-c59749a2c136

**Smartphone (please complete the following information):**
 - Device: Infinix Note 30 Pro
 - Android version: Android 13
 - App version: Latest from F-Droid

**Additional context**
nothing ..

**Comment by JorisBodin** [comment]
Thanks you for your feedback

We realised that our application did not open this link : https://welcome.infomaniak.com/error/ikmail/europe_only
We will soon be opening up free account creation to other countries.
In the meantime, with a vpn it works ...

We push a fix to display this error correctly
