### ISSUE TITLE
Mail text in dark mode is black

### ISSUE THREAD

**Issue by Brokoli5191** [Infomaniak/android-kMail#1448]
**Description**
In dark mode email text is black.

**Steps to reproduce**
1. Set app to dark mode
2. Click on an email
3. See that the text is black

**Expected behavior**
The text should be white

**Screenshots**
 
![Screenshot_20231008-105850_Infomaniak Mail](https://github.com/Infomaniak/android-kMail/assets/119419930/071bc090-4582-48d6-9b7f-1ff115bc93ed)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A12
 - Android version: Android 12
 - App version: 1.0.14

**Comment by JorisBodin** [comment]
Is this the official android version from samsung? Or a custom rom?

Have you updated your webview correctly?

**Comment by Brokoli5191** [comment]
Webview was not on the newest version because i never had problems. After updating webview all good.
