### ISSUE TITLE
"VIP" feature request

### ISSUE THREAD

**Issue by angvoreeth** [Infomaniak/android-kMail#1577]
Dears,

As an end user, I would like to have the VIP feature added.

This feature would work like the favourite one but email-based this time. The goal would be to quickly find all the emails of a VIP.

Example:
I receive an email from doctor@hospital.be. this address is added in the VIP by clicking on an icon next to the address (perhaps just before the date ?).

Suggestion: 
In the Search functionality, add "VIP" as a tag. When clicking on the tag, show all the VIP's. Then the user can choose easily which emails to find and show.

Thanks.

**Comment by JorisBodin** [comment]
Dear angvoreeth,

Thank you for sharing your idea with us! We've noted your suggestion to add a VIP feature to our platform and are pleased to let you know that it's now part of our backlog. While we don't have a specific timeline yet, we'll be sure to update you when development begins.

In the meantime, we're working on some exciting new features that we think you'll love. Stay tuned for more updates coming soon!
