### ISSUE TITLE
Can't log in with OTP

### ISSUE THREAD

**Issue by Yaya-Cout** [Infomaniak/android-kMail#1624]
**Description**
I installed the latest version of the application from F-Droid (1.1.3) and I tried to log in. When I type the correct mail address and password, I briefly see the page asking for my OTP code, then the page is closed and a message saying "Internet Connection problem" is shown.

**Steps to reproduce**
1. Enable OTP on an account
2. Install the application
3. Type the email and password

**Expected behavior**
The OTP page should stay displayed.

**Screenshots**
![Error message](https://github.com/Infomaniak/android-kMail/assets/67095734/f5385bc6-fdea-444c-b7b1-cbff0a1957ac)

**Smartphone**
 - Device: Google Pixel 6a
 - Android version: Android 14 (GrapheneOS)
 - App version: 1.1.3

**Additional context**
Since Free blocked my account (because I used Tor once), I have no longer to stay on K9-Mail which support IMAP on any mail account.
I haven't installed Google Play Services on my phone.
When I try to create a new email from the application, I have the same error (Internet Connection problem).

**Comment by Yaya-Cout** [comment]
I am closing this issue since I reinstalled the app, and it's now working without problem.
I don't think it's related to it, but I built the app from source (`./gradlew installFdroidDebug`), saw that the connection was working, uninstalled the app to reinstall the F-Droid version and it was also working. I have no idea what happened.
Sorry about the inconvenience.

**Comment by JorisBodin** [comment]
I was in the process of replying to you

But if it displays this error message, there's definitely a problem with your connection. Possibly an ad blocker etc ...
