### ISSUE TITLE
Notification patch

### ISSUE THREAD

**Issue by ctout76** [Infomaniak/android-kMail#1956]
Hello, 

The notification badge is no longer displayed on the icon of the Infomaniak Mail v1.3.4 application, same problem with the previous version.

(Pixel 8a GrapheneOS Android 14)

**Comment by tevincent** [comment]
Hello,

By default, we don't display it. You can change that settings here:

![Screenshot_20240711_101934](https://github.com/Infomaniak/android-kMail/assets/149579879/f7f8c7b3-acea-4dcd-a87a-11e438abbc14)

We'll try to fix that issue.

**Comment by ctout76** [comment]
Thank you !
