### ISSUE TITLE
Subject comes twice on notification

### ISSUE THREAD

**Issue by MaFarine** [Infomaniak/android-kMail#899]
**Description**
When I receive an email I get the subject written twice on the notification center.

**Steps to reproduce**
1. Receive an email
2. Slide down the notification center.
3. See error

**Expected behavior**
I would like to have the subject written only once and part of the body shown.

**Screenshots**
![kmail-subjectComesTwice.png.jpg](https://user-images.githubusercontent.com/82103273/234765999-69857381-23bd-4938-a7b5-3c3664bc0a63.jpg)

**Smartphone:**
 - Device: Fairphone 3
 - Android version: 12 on e/os/ 1.9.1
 - App version: 1.0.0-beta5

**Comment by JorisBodin** [comment]
It's not a bug, it's that the subject of the email and the first visible sentence in the email is the same.
The notification shows the subject and the beginning of the email
<img width="790" alt="image" src="https://user-images.githubusercontent.com/2796439/235452822-5e86d7c8-0d04-48f3-817b-078a3e5b56c4.png">

**Comment by MaFarine** [comment]
Oh right..

Sorry about that!

Have a nice day
