### ISSUE TITLE
Suggested contacts - automatically save email addresses

### ISSUE THREAD

**Issue by Tommixe** [Infomaniak/android-kMail#906]
When you start typing someone's name in a new email, contacts present in your phone contact app shows up as suggestions.
If you want to send a new email to a someone form which you have recently received an email, you need first to save the new address on the contact app and then it will show up as suggestion.

It would be nice that new email addresses are automatically saved in the contact app when a new mail is received.
In this way they will show up as suggestion when composing a new mail.

**Comment by JorisBodin** [comment]
It displays the contacts of the phone, those of the workspace but also the suggestions in relation to those that we have sent from emails.

Do you have an example that doesn't work?

**Comment by Tommixe** [comment]
Hi, actually suggestions in relation to sent emails are not shown

This is the use case:
1. I receive an email from a new address
2. I reply to this email
3. I compose a new email and start typing the new email address into the "to" field
5. The new email address is not suggested

Using kMail application from Fdroid and running Android 11.

**Comment by JorisBodin** [comment]
Each time you launch the app, it computes the contacts, so you'll get the new suggestions.
