### ISSUE TITLE
New message ask Security (finger print) 

### ISSUE THREAD

**Issue by grumpy-one** [Infomaniak/android-kMail#993]
**Description**
When I want to write a new mail, thé app ask me finger print... 

**Steps to reproduce**
Just click on 'New message' 

**Expected behavior**
Just write an email

**Screenshots**
Not need I think

**Smartphone (please complete the following information):**
 - Device: Nothing Phone (1)
 - Android version: Android 13
 - App version: 1-0-0 beta 8

**Comment by grumpy-one** [comment]
Same to open a draft...

**Comment by sirambd** [comment]
Already fixed in the latest version **kMail(1.0.0beta11) or higher**.
