### ISSUE TITLE
Can't send a mail with extern mail address

### ISSUE THREAD

**Issue by grumpy-one** [Infomaniak/android-kMail#994]
**Description**
Send buton doesn't work when I click on a mail adress from my browser

**Steps to reproduce**
From another app, choose kMail to write a mail and try to send it. 

**Expected behavior**
Send my email

**Screenshots**
Not need I think

**Smartphone (please complete the following information):**
 - Device: Nothing Phone (1)
 - Android version: Android 13
 - App version: 1.0.0-beta8

**Additional context**
For me, kMail think I don't put any mail adress on the field 'to'.

**Comment by sirambd** [comment]
@grumpy-one Can you try with the latest version of **kMail (1.0.0-beta11)** please, and let us know if you still have the problem.

**Comment by grumpy-one** [comment]
@sirambd I do a test and it's ok
