### ISSUE TITLE
Choose an adress to send an email

### ISSUE THREAD

**Issue by grumpy-one** [Infomaniak/android-kMail#995]
**Is your feature request related to a problem? Please describe.**
When I click on a mail address from another app, kMail choose the first mail address of my account. 

**Describe the solution you'd like**
I want to choose the mail address 

**Describe alternatives you've considered**
Or add an option about that on the app settings

**Comment by JorisBodin** [comment]
Duplicated with https://github.com/Infomaniak/android-kMail/issues/997
