### ISSUE TITLE
Can't choose an alias

### ISSUE THREAD

**Issue by grumpy-one** [Infomaniak/android-kMail#997]
**Description**
I can't change my address mail for one of my alias
For me it's a bug, because I choose a signature by default to be use with an alias, but isn't what I see on the app, I always see the main address mail

**Steps to reproduce**
N/a

**Expected behavior**
Clic on the field 'from' to choose an alias. 

**Screenshots**
N/a

**Smartphone (please complete the following information):**
 - Device: Nothing Phone (1)
 - Android version: Android 13 
 - App version: 1.0.0-beta8

**Additional context**
N/a

**Comment by mprasil** [comment]
I'm also waiting for this one before I can use the app. I think that's planned for the 2.0 milestone - see #88.

**Comment by JorisBodin** [comment]
The [1.0.5](https://github.com/Infomaniak/android-kMail/releases/tag/1.0.5) add this feature
It will be available within 1-2 hours
