### ISSUE TITLE
Multiple draft

### ISSUE THREAD

**Issue by grumpy-one** [Infomaniak/android-kMail#998]
**Description**
One mail but multiple drafts if we write a mail and we change to another app and come back to the kMail to continue writing.

**Steps to reproduce**
1. On kMail, start a new mail
2. Go to another app
3. Wait a litlle (like taking some informations) 
4. Come back to kMail on your mail
5. Check the draft folder 

**Expected behavior**
Just have one draft

**Screenshots**
Video private if you want

**Smartphone (please complete the following information):**
 - Device: Nothing Phone (1)
 - Android version: Android 13
 - App version: 1.0.0-beta8

**Additional context**

**Comment by JorisBodin** [comment]
https://github.com/Infomaniak/android-kMail/pull/1015
